# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=175, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FruitSalesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('sold_date', models.DateTimeField()),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('fruitinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='fruitsales.FruitInfo')),
            ],
        ),
    ]
